id: PC3E75931
initial_creation_type: input
source_metadata:
  title: Dhāraṇī Series
  language: en
  description: 'A selection of texts related to dhāraṇī (gzungs), mantric formulae
    or incantations:'
  volume:
    f0192db486064ffea4b5d29e72c7d072:
      title: The Dhāraṇī of Amitāyus
      parent: Amitāyus
    36c0be0433354ff7a0e7e945d59e74f1:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Blazing Wheel
    94b9d6f2ace448ac89e3618028f7f27e:
      title: The Noble Essence of Dependent Origination
      parent: Dependent Origination
    c284f6fdd6e444ea8ce335fb1dd89a7c:
      title: Dhāraṇī of Goddess Parṇaśavarī
      parent: Parṇaśavarī
    259c120f3547465e830b3a171e1e2c7f:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Sitātapatrā
    0567dbd09372483487983c649de55504:
      title: The Noble Mārīcī Dhāraṇī
      parent: Mārīcī
    55212bb0dd3449de8ddcbde476883d0e:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Vajrapāṇi
    34e7d9863cdd4b738e7f6b59da8638a9:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Vajravidāraṇa
    db7395c3a9aa48258952220633db8606:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Various
    bb6f4e42b8cf4dd492ae7c85ef53c7e9:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Vasudhārā
    ddc8e11190bf4a51b35058dbe1601e83:
      title: The Dhāraṇī of Glorious Vajraṇakhī
      parent: Vajraṇakhī
    8bed6dfe91474e7ea2f9d950bd391095:
      title: Brief Dhāraṇī of Glorious Vajraṇakhī
      parent: Vajraṇakhī
created_at: '2022-03-01T03:25:10.944476'
last_modified_at: '2022-03-01T03:25:10.944482'
